#!/usr/bin/env Rscript
# Write `altdoc/quarto_website.yml` from `tools/reference-groups.yml`.
#
# The sidebar holds 51 topics in 8 groups and is generated rather than typed, so there is
# no second list to drift from the first. altdoc's own `$ALTDOC_MAN_BLOCK` placeholder
# would give one flat list of 182 items, which is what the spike measured before this.
#
# Run it after adding or renaming an exported function, and the test in
# tests/testthat/test-reference-groups.R says so if you forget.

groups <- yaml::read_yaml("tools/reference-groups.yml")$groups

reference <- unlist(lapply(groups, function(group) {
  c(
    sprintf('          - section: "%s"', group$title),
    "            contents:",
    sprintf("              - man/%s.qmd", unlist(group$contents))
  )
}))

# $ALTDOC_VIGNETTE_BLOCK is substituted only where altdoc expects it - as a `section:` in
# the sidebar. Used as a navbar `file:` it survives as a literal string and Quarto then
# waits on a file by that name: no error, no CPU, and `docs/` already emptied.
# The About section is built from what is there. altdoc substitutes `$ALTDOC_LICENSE` and
# friends only when the file exists, and an unsubstituted placeholder becomes a sidebar
# entry that cannot be clicked - which is what happened to Licence and Changelog: the
# template carried `$ALTDOC_LICENCE` while this repository spells it LICENSE, and named a
# CHANGELOG this repository does not have (no NEWS.md either, because there has been no
# formal release). altdoc's own default config lists both spellings for exactly this
# reason and I kept one of them.
#
# Deriving it means the entry cannot outlive the file.
# The placeholder is NOT ours to choose: altdoc builds it from the basename of whichever
# file it found, so NEWS.md is $ALTDOC_NEWS and CHANGELOG.md is $ALTDOC_CHANGELOG. Naming
# one while shipping the other is the same broken entry by a longer route, so the
# placeholder is derived here by altdoc's own rule rather than written out beside the file.
#
# The order is the one pyplatypus's sidebar uses, so a reader moving between the two sites
# finds the same four things in the same places.
candidates <- list(
  list(text = "Changelog", files = c("CHANGELOG.md", "NEWS.md")),
  list(text = "Code of conduct", files = "CODE_OF_CONDUCT.md"),
  list(text = "Licence", files = c("LICENSE.md", "LICENSE")),
  # altdoc writes a citation page from DESCRIPTION, so this one needs no file of its own.
  list(text = "Citation", placeholder = "$ALTDOC_CITATION", files = NULL)
)

about <- unlist(lapply(candidates, function(entry) {
  found <- if (is.null(entry$files)) NULL else entry$files[file.exists(entry$files)]
  if (!is.null(entry$files) && length(found) == 0L) {
    cat("About: skipping", entry$text, "- no", paste(entry$files, collapse = " or "), "\n")
    return(NULL)
  }
  placeholder <- entry$placeholder
  if (is.null(placeholder)) {
    placeholder <- sprintf("$ALTDOC_%s", toupper(tools::file_path_sans_ext(found[1])))
  }
  cat("About:", entry$text, "->", placeholder, "\n")
  c(sprintf("          - text: %s", entry$text),
    sprintf("            file: %s", placeholder))
}))

template <- c(
  "# GENERATED by tools/build-reference.R from tools/reference-groups.yml. Do not edit:",
  "# the reference grouping is a judgement and lives in that file, not in this one.",
  "",
  "project:",
  "  type: website",
  "  output-dir: ../docs/",
  "",
  "# One file, identical in both repositories, so the two sites look alike by",
  "# construction rather than by anybody remembering to copy a colour. The Quarto",
  "# project is _quarto/, so the brand file is one level up at the repository root.",
  "brand: ../_brand.yml",
  "",
  "# The pipeline renders twice: altdoc converts Rd to qmd and renders, then",
  "# tools/polish-docs.R restores the cross-reference links and the code fences and",
  "# Quarto renders again. Freezing means the second pass reuses the first pass's",
  "# executed chunks instead of running 20 R examples over - which is most of the time.",
  "execute:",
  "  freeze: auto",
  "",
  "website:",
  '  title: "$ALTDOC_PACKAGE_NAME"',
  "  code-links: true",
  "  # Not in _brand.yml on purpose: the sticker lives where this package already keeps",
  "  # its images, and copying a binary so one path works in two repositories is worse",
  "  # than naming it in each.",
  "  favicon: ../man/figures/hexsticker_platypus.png",
  "  navbar:",
  "    search: true",
  "    right:",
  "      - icon: github",
  "        href: $ALTDOC_PACKAGE_URL_GITHUB",
  "        aria-label: $ALTDOC_PACKAGE_NAME GitHub",
  "  sidebar:",
  "    style: docked",
  "    collapse-level: 2",
  "    contents:",
  "      - text: Home",
  "        file: index.md",
  "      - section: $ALTDOC_VIGNETTE_BLOCK",
  '      - section: "Reference"',
  "        contents:",
    # First, as on the engine's site: the groups' descriptions live on that page and
    # the sidebar has nowhere to show them.
    "          - text: Overview",
    "            file: overview.qmd",
  reference,
  '      - section: "About"',
  "        contents:",
  about,
  "",
  "format:",
  "  html:",
  "    code-link: true",
  "    toc: true",
  ""
)

dir.create("altdoc", showWarnings = FALSE)
writeLines(template, "altdoc/quarto_website.yml")
cat("altdoc/quarto_website.yml:", length(groups), "groups,",
    sum(lengths(lapply(groups, `[[`, "contents"))), "topics\n")

# The Overview page, which a sidebar cannot be: a sidebar shows titles, and this shows what
# each group is for. Those `desc` fields have been in reference-groups.yml since it was
# written and were rendered nowhere; pyplatypus has had the equivalent all along, because
# quartodoc generates one from the same grouping.
#
# Written into `_quarto/` rather than `altdoc/`: altdoc copies `altdoc/` into `docs/` *after*
# rendering, so a page left there would be published with no theme and no navigation, while
# `render_docs()` only creates `_quarto/` and never empties it - read out of its source rather
# than assumed. The project block names no `render:` list, so Quarto renders what is in there.
overview <- c(
  "---",
  'title: "Overview"',
  "---",
  "",
  "<!-- GENERATED by tools/build-reference.R from tools/reference-groups.yml. -->",
  "",
  "Every exported function, grouped by what you are doing. The same groups in the same order",
  "as [the engine's reference](https://maju116.github.io/pyplatypus/reference/), each side",
  "showing the ones it has.",
  ""
)
for (group in groups) {
  overview <- c(
    overview,
    sprintf("## %s", group$title),
    "",
    trimws(group$desc),
    "",
    sprintf("- [`%s`](man/%s.html)", unlist(group$contents), unlist(group$contents)),
    ""
  )
}
dir.create("_quarto", showWarnings = FALSE)
writeLines(overview, "_quarto/overview.qmd")
cat("_quarto/overview.qmd:", length(overview), "lines,",
    sum(lengths(lapply(groups, `[[`, "contents"))), "links\n")
