#!/usr/bin/env Rscript
# Write `altdoc/quarto_website.yml` from `tools/reference-groups.yml`.
#
# The sidebar holds 51 topics in 8 groups and is generated rather than typed, so there is
# no second list to drift from the first. altdoc's own `$ALTDOC_MAN_BLOCK` placeholder
# would give one flat list of 182 items, which is what the spike measured before this.
#
# Run it after adding or renaming an exported function, and the test in
# tests/testthat/test-reference-groups.R says so if you forget.

groups <- yaml::read_yaml("tools/reference-groups.yml")$groups

reference <- unlist(lapply(groups, function(group) {
  c(
    sprintf('          - section: "%s"', group$title),
    "            contents:",
    sprintf("              - man/%s.qmd", unlist(group$contents))
  )
}))

# $ALTDOC_VIGNETTE_BLOCK is substituted only where altdoc expects it - as a `section:` in
# the sidebar. Used as a navbar `file:` it survives as a literal string and Quarto then
# waits on a file by that name: no error, no CPU, and `docs/` already emptied.
template <- c(
  "# GENERATED by tools/build-reference.R from tools/reference-groups.yml. Do not edit:",
  "# the reference grouping is a judgement and lives in that file, not in this one.",
  "",
  "project:",
  "  type: website",
  "  output-dir: ../docs/",
  "",
  "# One file, identical in both repositories, so the two sites look alike by",
  "# construction rather than by anybody remembering to copy a colour. The Quarto",
  "# project is _quarto/, so the brand file is one level up at the repository root.",
  "brand: ../_brand.yml",
  "",
  "# The pipeline renders twice: altdoc converts Rd to qmd and renders, then",
  "# tools/polish-docs.R restores the cross-reference links and the code fences and",
  "# Quarto renders again. Freezing means the second pass reuses the first pass's",
  "# executed chunks instead of running 20 R examples over - which is most of the time.",
  "execute:",
  "  freeze: auto",
  "",
  "website:",
  '  title: "$ALTDOC_PACKAGE_NAME"',
  "  code-links: true",
  "  # Not in _brand.yml on purpose: the sticker lives where this package already keeps",
  "  # its images, and copying a binary so one path works in two repositories is worse",
  "  # than naming it in each.",
  "  favicon: ../man/figures/hexsticker_platypus.png",
  "  navbar:",
  "    search: true",
  "    right:",
  "      - icon: github",
  "        href: $ALTDOC_PACKAGE_URL_GITHUB",
  "        aria-label: $ALTDOC_PACKAGE_NAME GitHub",
  "  sidebar:",
  "    style: docked",
  "    collapse-level: 2",
  "    contents:",
  "      - text: Home",
  "        file: index.md",
  "      - section: $ALTDOC_VIGNETTE_BLOCK",
  '      - section: "Reference"',
  "        contents:",
  reference,
  '      - section: "About"',
  "        contents:",
  "          - text: Changelog",
  "            file: $ALTDOC_CHANGELOG",
  "          - text: Licence",
  "            file: $ALTDOC_LICENCE",
  "          - text: Code of conduct",
  "            file: $ALTDOC_CODE_OF_CONDUCT",
  "          - text: Citation",
  "            file: $ALTDOC_CITATION",
  "",
  "format:",
  "  html:",
  "    code-link: true",
  "    toc: true",
  ""
)

dir.create("altdoc", showWarnings = FALSE)
writeLines(template, "altdoc/quarto_website.yml")
cat("altdoc/quarto_website.yml:", length(groups), "groups,",
    sum(lengths(lapply(groups, `[[`, "contents"))), "topics\n")
